# Generated by Django 4.1.7 on 2023-09-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_echantillon', models.IntegerField(unique=True)),
                ('quantite', models.FloatField()),
                ('date_prelevement', models.DateField()),
                ('date_reception', models.DateField()),
                ('observation', models.TextField()),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.laboratoire')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.location')),
            ],
        ),
    ]
