# Generated by Django 4.1.7 on 2023-09-12 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_location_echantillon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_analyse', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_analyse',
            },
        ),
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_produit', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_produit',
            },
        ),
        migrations.CreateModel(
            name='ProductEngrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateField()),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.echantillon')),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.laboratoire')),
            ],
        ),
    ]
