# Generated by Django 4.1.7 on 2023-09-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanalyse',
            name='num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
