# Generated by Django 4.1.7 on 2023-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_laborantins_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborantins',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
