# Generated by Django 4.1.7 on 2023-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_laborantins_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborantins',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to=''),
        ),
    ]
